apiVersion: v2
name: website
description: A Helm chart for deploying a website to Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"

maintainers:
  - name: Uday Kumar
    email: udaybkumar083@outlook.com